export default {
  path: '/collection',
  name: 'collection',
  redirect: '/collection/guide',
  meta: {
    order: 2,
    icon: 'IEpBriefcase',
    title: '高速上云',
    isLink: '',
    isHide: false,
    isFull: false,
    isAffix: false,
    isKeepAlive: true,
  },
  children: [
    {
      path: '/collection/guide',
      name: 'guide',
      component: '/collection/guide/index',
      meta: {
        title: '云网络',
        icon: 'IEpMenu',
        isLink: '',
        isHide: false,
        isFull: false,
        isAffix: false,
        isKeepAlive: true,
      },
    },
    {
      path: '/collection/guide1',
      name: 'guide1',
      component: '/collection/guide/index',
      meta: {
        icon: 'IEpMenu',
        title: 'SD-Wan上云',
        isLink: '',
        isHide: false,
        isFull: false,
        isAffix: false,
        isKeepAlive: true,
      },
    },
    {
      path: '/collection/guide2',
      name: 'guide2',
      component: '/collection/guide/index',
      meta: {
        icon: 'IEpMenu',
        title: ' 运营报告',
        isLink: '',
        isHide: false,
        isFull: false,
        isAffix: false,
        isKeepAlive: true,
      },
    },
    {
      path: '/collection/guide3',
      name: 'guide3',
      component: '/collection/guide/index',
      meta: {
        icon: 'IEpMenu',
        title: '告警记录',
      },
    },
    {
      path: '/collection/guide4',
      name: 'guide4',
      component: '/collection/guide/index',
      meta: {
        icon: 'IEpMenu',
        title: '故障演练',
        isLink: '',
      },
    },
    {
      path: '/collection/guide5',
      name: 'guide5',
      component: '/collection/guide/index',
      meta: {
        icon: 'IEpMenu',
        title: '速度测试',
      },
    },
    {
      path: '/collection/guide6',
      name: 'guide6',
      component: '/collection/guide/index',
      meta: {
        icon: 'IEpMenu',
        title: ' 运维工具',
      },
    },
  ],
}
