export default {
  path: '/directives',
  name: 'directives',
  redirect: '/directives/copyDirect',
  meta: {
    order: 4,
    icon: 'IEpStamp',
    title: '客户端',
    isLink: '',
    isHide: false,
    isFull: false,
    isAffix: false,
    isKeepAlive: true,
  },
  children: [
    {
      path: '/directives/copyDirect',
      name: 'copyDirect',
      component: '/directives/copyDirect/index',
      meta: {
        icon: 'IEpMenu',
        title: '客户端接入节点',
        isLink: '',
        isHide: false,
        isFull: false,
        isAffix: false,
        isKeepAlive: true,
      },
    },
    {
      path: '/directives/watermarkDirect',
      name: 'watermarkDirect',
      component: '/directives/watermarkDirect/index',
      meta: {
        icon: 'IEpMenu',
        title: '账号',
        isLink: '',
        isHide: false,
        isFull: false,
        isAffix: false,
        isKeepAlive: true,
      },
    },
    {
      path: '/directives/dragDirect',
      name: 'dragDirect',
      component: '/directives/dragDirect/index',
      meta: {
        icon: 'IEpMenu',
        title: '终端',
        isLink: '',
        isHide: false,
        isFull: false,
        isAffix: false,
        isKeepAlive: true,
      },
    },
    {
      path: '/directives/debounceDirect',
      name: 'debounceDirect',
      component: '/directives/debounceDirect/index',
      meta: {
        icon: 'IEpMenu',
        title: '下载',
        isLink: '',
        isHide: false,
        isFull: false,
        isAffix: false,
        isKeepAlive: true,
      },
    },
    // {
    //   path: '/directives/throttleDirect',
    //   name: 'throttleDirect',
    //   component: '/directives/throttleDirect/index',
    //   meta: {
    //     icon: 'IEpMenu',
    //     title: '节流指令',
    //     isLink: '',
    //     isHide: false,
    //     isFull: false,
    //     isAffix: false,
    //     isKeepAlive: true,
    //   },
    // },
    // {
    //   path: '/directives/longpressDirect',
    //   name: 'longpressDirect',
    //   component: '/directives/longpressDirect/index',
    //   meta: {
    //     icon: 'IEpMenu',
    //     title: '长按指令',
    //     isLink: '',
    //     isHide: false,
    //     isFull: false,
    //     isAffix: false,
    //     isKeepAlive: true,
    //   },
    // },
    // {
    //   path: '/directives/slideinDirect',
    //   name: 'slideinDirect',
    //   component: '/directives/slideinDirect/index',
    //   meta: {
    //     icon: 'IEpMenu',
    //     title: '缓动上升',
    //     isLink: '',
    //     isHide: false,
    //     isFull: false,
    //     isAffix: false,
    //     isKeepAlive: true,
    //   },
    // },
    // {
    //   path: '/directives/loadingDirect',
    //   name: 'loadingDirect',
    //   component: '/directives/loadingDirect/index',
    //   meta: {
    //     icon: 'IEpMenu',
    //     title: '加载指令',
    //     isLink: '',
    //     isHide: false,
    //     isFull: false,
    //     isAffix: false,
    //     isKeepAlive: true,
    //   },
    // },

  ],
}
