export default {
  path: '/auth',
  name: 'auth',
  redirect: '/auth/menu',
  meta: {
    order: 5,
    icon: 'IEpLock',
    title: '权限管理',
    isLink: '',
    isHide: false,
    isFull: false,
    isAffix: false,
    isKeepAlive: true,
  },
  children: [
    {
      path: '/auth/menu',
      name: 'authMenu',
      component: '/auth/menu/index',
      meta: {
        icon: 'IEpMenu',
        title: '菜单权限',
        isLink: '',
        isHide: false,
        isFull: false,
        isAffix: false,
        isKeepAlive: true,
      },
    },
    {
      path: '/auth/button',
      name: 'authButton',
      component: '/auth/button/index',
      meta: {
        icon: 'IEpMenu',
        title: '按钮权限',
        isLink: '',
        isHide: false,
        isFull: false,
        isAffix: false,
        isKeepAlive: true,
      },
    },
  ],
}
