export default {
  path: '/collection',
  name: 'collection',
  redirect: '/collection/guide',
  meta: {
    order: 2,
    icon: 'IEpBriefcase',
    title: '常用组件',
    isLink: '',
    isHide: false,
    isFull: false,
    isAffix: false,
    isKeepAlive: true,
  },
  children: [
    {
      path: '/collection/guide',
      name: 'guide',
      component: '/collection/guide/index',
      meta: {
        icon: 'IEpMenu',
        title: '引导页',
        isLink: '',
        isHide: false,
        isFull: false,
        isAffix: false,
        isKeepAlive: true,
      },
    },
    {
      path: '/collection/tabs',
      name: 'tabs',
      component: '/collection/tabs/index',
      meta: {
        icon: 'IEpMenu',
        title: '标签页操作',
        isLink: '',
        isHide: false,
        isFull: false,
        isAffix: false,
        isKeepAlive: true,
      },
      children: [
        {
          path: '/collection/tabs/detail/:id',
          name: 'tabsDetail',
          component: '/collection/tabs/detail',
          meta: {
            icon: 'IEpMenu',
            title: 'Tab 详情',
            activeMenu: '/collection/tabs',
            isLink: '',
            isHide: true,
            isFull: false,
            isAffix: false,
            isKeepAlive: true,
          },
        },
      ],
    },
    {
      path: '/collection/selectIcon',
      name: 'selectIcon',
      component: '/collection/selectIcon/index',
      meta: {
        icon: 'IEpMenu',
        title: '图标选择器',
        isLink: '',
        isHide: false,
        isFull: false,
        isAffix: false,
        isKeepAlive: true,
      },
    },
    {
      path: '/collection/selectFilter',
      name: 'selectFilter',
      component: '/collection/selectFilter/index',
      meta: {
        icon: 'IEpMenu',
        title: '分类筛选器',
        isLink: '',
        isHide: false,
        isFull: false,
        isAffix: false,
        isKeepAlive: true,
      },
    },
    {
      path: '/collection/treeFilter',
      name: 'treeFilter',
      component: '/collection/treeFilter/index',
      meta: {
        icon: 'IEpMenu',
        title: '树形筛选器',
        isLink: '',
        isHide: false,
        isFull: false,
        isAffix: false,
        isKeepAlive: true,
      },
    },
    {
      path: '/collection/svgIcon',
      name: 'svgIcon',
      component: '/collection/svgIcon/index',
      meta: {
        icon: 'IEpMenu',
        title: 'SVG 图标',
        isLink: '',
        isHide: false,
        isFull: false,
        isAffix: false,
        isKeepAlive: true,
      },
    },
    {
      path: '/collection/uploadFile',
      name: 'uploadFile',
      component: '/collection/uploadFile/index',
      meta: {
        icon: 'IEpMenu',
        title: '文件上传',
        isLink: '',
        isHide: false,
        isFull: false,
        isAffix: false,
        isKeepAlive: true,
      },
    },
    {
      path: '/collection/batchImport',
      name: 'batchImport',
      component: '/collection/batchImport/index',
      meta: {
        icon: 'IEpMenu',
        title: '批量添加数据',
        isLink: '',
        isHide: false,
        isFull: false,
        isAffix: false,
        isKeepAlive: true,
      },
    },
    {
      path: '/collection/draggable',
      name: 'draggable',
      component: '/collection/draggable/index',
      meta: {
        icon: 'IEpMenu',
        title: '拖拽组件',
        isLink: '',
        isHide: false,
        isFull: false,
        isAffix: false,
        isKeepAlive: true,
      },
    },
  ],
}
