export default {
  path: '/directives',
  name: 'directives',
  redirect: '/directives/copyDirect',
  meta: {
    order: 3,
    icon: 'IEpStamp',
    title: '自定义指令',
    isLink: '',
    isHide: false,
    isFull: false,
    isAffix: false,
    isKeepAlive: true,
  },
  children: [
    {
      path: '/directives/copyDirect',
      name: 'copyDirect',
      component: '/directives/copyDirect/index',
      meta: {
        icon: 'IEpMenu',
        title: '复制指令',
        isLink: '',
        isHide: false,
        isFull: false,
        isAffix: false,
        isKeepAlive: true,
      },
    },
    {
      path: '/directives/watermarkDirect',
      name: 'watermarkDirect',
      component: '/directives/watermarkDirect/index',
      meta: {
        icon: 'IEpMenu',
        title: '水印指令',
        isLink: '',
        isHide: false,
        isFull: false,
        isAffix: false,
        isKeepAlive: true,
      },
    },
    {
      path: '/directives/dragDirect',
      name: 'dragDirect',
      component: '/directives/dragDirect/index',
      meta: {
        icon: 'IEpMenu',
        title: '拖拽指令',
        isLink: '',
        isHide: false,
        isFull: false,
        isAffix: false,
        isKeepAlive: true,
      },
    },
    {
      path: '/directives/debounceDirect',
      name: 'debounceDirect',
      component: '/directives/debounceDirect/index',
      meta: {
        icon: 'IEpMenu',
        title: '防抖指令',
        isLink: '',
        isHide: false,
        isFull: false,
        isAffix: false,
        isKeepAlive: true,
      },
    },
    {
      path: '/directives/throttleDirect',
      name: 'throttleDirect',
      component: '/directives/throttleDirect/index',
      meta: {
        icon: 'IEpMenu',
        title: '节流指令',
        isLink: '',
        isHide: false,
        isFull: false,
        isAffix: false,
        isKeepAlive: true,
      },
    },
    {
      path: '/directives/longpressDirect',
      name: 'longpressDirect',
      component: '/directives/longpressDirect/index',
      meta: {
        icon: 'IEpMenu',
        title: '长按指令',
        isLink: '',
        isHide: false,
        isFull: false,
        isAffix: false,
        isKeepAlive: true,
      },
    }, {
      path: '/directives/slideinDirect',
      name: 'slideinDirect',
      component: '/directives/slideinDirect/index',
      meta: {
        icon: 'IEpMenu',
        title: '缓动上升',
        isLink: '',
        isHide: false,
        isFull: false,
        isAffix: false,
        isKeepAlive: true,
      },
    },

  ],
}
