export default {
  path: '/link',
  name: 'link',
  redirect: '/link/gitee',
  meta: {
    order: 6,
    icon: 'IEpPaperclip',
    title: '外部链接',
    isLink: '',
    isHide: false,
    isFull: false,
    isAffix: false,
    isKeepAlive: true,
  },
  children: [
    {
      path: '/link/gitee',
      name: 'gitee',
      component: '/link/gitee/index',
      meta: {
        icon: 'IEpMenu',
        title: 'Gitee 仓库',
        isLink: 'https://gitee.com/fxzer/x-admin.git',
        isHide: false,
        isFull: false,
        isAffix: false,
        isKeepAlive: true,
      },
    },
    {
      path: '/link/github',
      name: 'github',
      component: '/link/github/index',
      meta: {
        icon: 'IEpMenu',
        title: 'GitHub 仓库',
        isLink: 'https://github.com/fxzer/x-admin.git',
        isHide: false,
        isFull: false,
        isAffix: false,
        isKeepAlive: true,
      },
    },
    {
      path: '/link/geekerDocs',
      name: 'geekerDocs',
      component: '/link/geekerDocs/index',
      meta: {
        icon: 'IEpMenu',
        title: '项目文档',
        isLink: 'https://docs.spicyboy.cn',
        isHide: false,
        isFull: false,
        isAffix: false,
        isKeepAlive: true,
      },
    },
    {
      path: '/link/juejin',
      name: 'juejin',
      component: '/link/juejin/index',
      meta: {
        icon: 'IEpMenu',
        title: '掘金主页',
        isLink: 'https://juejin.cn/user/3263814531551816/posts',
        isHide: false,
        isFull: false,
        isAffix: false,
        isKeepAlive: true,
      },
    },
  ],
}
