export default {
  path: '/menu',
  name: 'menu',
  redirect: '/menu/menu1',
  meta: {
    order: 8,
    icon: 'IEpList',
    title: '菜单嵌套',
    isLink: '',
    isHide: false,
    isFull: false,
    isAffix: false,
    isKeepAlive: true,
  },
  children: [
    {
      path: '/menu/menu1',
      name: 'menu1',
      component: '/menu/menu1/index',
      meta: {
        icon: 'IEpMenu',
        title: '菜单1',
        isLink: '',
        isHide: false,
        isFull: false,
        isAffix: false,
        isKeepAlive: true,
      },
    },
    {
      path: '/menu/menu2',
      name: 'menu2',
      redirect: '/menu/menu2/menu21',
      meta: {
        icon: 'IEpMenu',
        title: '菜单2',
        isLink: '',
        isHide: false,
        isFull: false,
        isAffix: false,
        isKeepAlive: true,
      },
      children: [
        {
          path: '/menu/menu2/menu21',
          name: 'menu21',
          component: '/menu/menu2/menu21/index',
          meta: {
            icon: 'IEpMenu',
            title: '菜单2-1',
            isLink: '',
            isHide: false,
            isFull: false,
            isAffix: false,
            isKeepAlive: true,
          },
        },
        {
          path: '/menu/menu2/menu22',
          name: 'menu22',
          redirect: '/menu/menu2/menu22/menu221',
          meta: {
            icon: 'IEpMenu',
            title: '菜单2-2',
            isLink: '',
            isHide: false,
            isFull: false,
            isAffix: false,
            isKeepAlive: true,
          },
          children: [
            {
              path: '/menu/menu2/menu22/menu221',
              name: 'menu221',
              component: '/menu/menu2/menu22/menu221/index',
              meta: {
                icon: 'IEpMenu',
                title: '菜单2-2-1',
                isLink: '',
                isHide: false,
                isFull: false,
                isAffix: false,
                isKeepAlive: true,
              },
            },
            {
              path: '/menu/menu2/menu22/menu222',
              name: 'menu222',
              component: '/menu/menu2/menu22/menu222/index',
              meta: {
                icon: 'IEpMenu',
                title: '菜单2-2-2',
                isLink: '',
                isHide: false,
                isFull: false,
                isAffix: false,
                isKeepAlive: true,
              },
            },
          ],
        },
        {
          path: '/menu/menu2/menu23',
          name: 'menu23',
          component: '/menu/menu2/menu23/index',
          meta: {
            icon: 'IEpMenu',
            title: '菜单2-3',
            isLink: '',
            isHide: false,
            isFull: false,
            isAffix: false,
            isKeepAlive: true,
          },
        },
      ],
    },
    {
      path: '/menu/menu3',
      name: 'menu3',
      component: '/menu/menu3/index',
      meta: {
        icon: 'IEpMenu',
        title: '菜单3',
        isLink: '',
        isHide: false,
        isFull: false,
        isAffix: false,
        isKeepAlive: true,
      },
    },
  ],
}
